intranet/box/urls.py
# URLconf
from django.urls import path

from . import views

app_name = 'box'
urlpatterns = [
    path('folders/', views.folder_sizes, name='folders'),
]

intranet/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('search/', views.search, name='search'),
]

intranet/home/models.py
from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.models import Page, Orderable
from wagtail.documents.blocks import DocumentChooserBlock
from wagtail.images.blocks import ImageChooserBlock


class Heading(blocks.CharBlock):
    class Meta:
        template = 'blocks/heading.html'
        icon = 'grip'
        label = 'Heading'


class GeneralPage(Page):
    body = StreamField(block_types=[
        ('heading', Heading(classname='full title')),
        ('paragraph', blocks.RichTextBlock(required=True, classname='paragraph')),
        ('image', ImageChooserBlock()),
        ('html', blocks.RawHTMLBlock()),
    ], blank=False)

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]


class TwoColumnGeneralPage(Page):
    body = StreamField(block_types=([
        ('heading', Heading(classname='full title')),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
        ('document', DocumentChooserBlock()),
        ('html', blocks.RawHTMLBlock()),
    ]), null=True, blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('body')
    ]


class HomePage(Page):
    pass

intranet/home/views.py
from django.shortcuts import render

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    if search_query:
        if request.user.is_staff:
            search_results = Page.objects.live().search(search_query)
        else:
            search_results = Page.objects.public().live().search(search_query)

        # Log the query so Wagtail can suggest promoted results
        Query.get(search_query).add_hit()
    else:
        search_results = Page.objects.none()

    return render(request, 'home/search_results.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

intranet/home/templates/home/general_page.html
{% extends 'base.html' %}
{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
    <div class="row-fluid">
        {% image page.banner original class="responsive" %}
    </div>
    <br>
    {% for block in page.body %}
        {% if block.block_type == 'tan_bg_text' %}
            <div class="tan-bg">
                {% include_block block %}
            </div>
        {% else %}
            {% include_block block %}
        {% endif %}
    {% endfor %}
{% endblock %}

intranet/home/templates/home/home_page.html
{% extends "base.html" %}
{% load static %}

{% block content_class %}h-100{% endblock %}

{% block content %}
    <div class="row align-items-center h-100">
        <div class="col h-100">
            <h3>Useful Links</h3>
            <ul>
                <li><a href="{% url 'box:folders' %}">Box Folder Sizes</a></li>
                {% if request.user.is_staff %}
                    <li><a href="https://intranet.redbutte.utah.edu/prometheus/targets">Prometheus Monitoring</a></li>
                    <li><a href="https://snipeit.intranet.redbutte.utah.edu">Snipe IT Inventory Management</a></li>
                {% endif %}
            </ul>
        </div>

        <div class="col justify-content-center">
            <h1>Red Butte Garden Intranet</h1>
        </div>

        <div class="col"></div>
    </div>
{% endblock content %}

intranet/home/templates/home/search_results.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description|safe }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% elif search_query %}
        No results found
    {% else %}
        Please type something into the search box
    {% endif %}
{% endblock %}